force-app/main/default/objects/Timeline_Configuration__c/Timeline_Configuration__c.object-meta.xml
<CustomObject>
    <label>Timeline Configuration</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Timeline Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Configuration__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>API Name of the object that this timeline configuration will be used.</description>
    <inlineHelpText>API Name of the object that this timeline configuration will be used.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddChildObjectToConfigControllerTest.cls
@isTest
public class AddChildObjectToConfigControllerTest {
    @testSetup static void setupTestData() {

        Timeline_Configuration__c timelineConf = new Timeline_Configuration__c(Object__c='Account');
        insert timelineConf;
    }

    @isTest static void testGetObjectName(){
        Timeline_Configuration__c conf = [select Id from Timeline_Configuration__c limit 1];
        String objName = AddChildObjectToConfigController.getObjectApiName(conf.Id);
        System.assert(objName.equals('Account'), 'Incorrect or null object name returned');
    }
}