force-app/main/default/objects/Timeline_Child_Object__c/Timeline_Child_Object__c.object-meta.xml
<CustomObject>
    <label>Timeline Child Object</label>
    <nameField>
        <displayFormat>TLC-{000000}</displayFormat>
        <label>Timeline Child Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Child Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Date_Field__c</fullName>
    <inlineHelpText>Field API Name that will be used to date and time part of the timeline. Created Date will be used as the default if this field isn&apos;t specified.</inlineHelpText>
    <label>Date Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Fields_to_Display__c.field-meta.xml
<CustomField>
    <fullName>Fields_to_Display__c</fullName>
    <inlineHelpText>Common separated list of fields to display in the detail section of the timeline component.</inlineHelpText>
    <label>Fields to Display</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <inlineHelpText>Standard Icon name (mainly used for standard objects) that have a corresponding icon at https://lightningdesignsystem.com/icons/#standard</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Child Object API Name</description>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Name__c</fullName>
    <inlineHelpText>Name of the relationship for the child object.</inlineHelpText>
    <label>Relationship Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Timeline_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Configuration__c</fullName>
    <label>Timeline Configuration</label>
    <referenceTo>Timeline_Configuration__c</referenceTo>
    <relationshipLabel>Timeline Child Objects</relationshipLabel>
    <relationshipName>Timeline_Child_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timeline_Child_Object__c/fields/Title_Field__c.field-meta.xml
<CustomField>
    <fullName>Title_Field__c</fullName>
    <inlineHelpText>Field that will be used as the title of the activity timeline.</inlineHelpText>
    <label>Title Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Configuration__c/Timeline_Configuration__c.object-meta.xml
<CustomObject>
    <label>Timeline Configuration</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Timeline Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Configuration__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>API Name of the object that this timeline configuration will be used.</description>
    <inlineHelpText>API Name of the object that this timeline configuration will be used.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordTimelineDataProviderTest.cls
@isTest

public with sharing class RecordTimelineDataProviderTest {
    @testSetup static void setupTestData() {

        Timeline_Configuration__c timelineConf = new Timeline_Configuration__c(Object__c='Account');
        insert timelineConf;
        Timeline_Child_Object__c childConf = new Timeline_Child_Object__c(  Date_Field__c='ActivityDate',
                                                                            Fields_To_Display__c='Subject,Description',
                                                                            Object__c='Task',
                                                                            Relationship_Name__c='Tasks',
                                                                            Icon_Name__c='standard:task',
                                                                            Title_Field__c='Subject',
                                                                            Timeline_Configuration__c=timelineConf.Id);
        insert childConf;
        Account acct = new Account(Name='My Timeline Test data account');
        insert acct;
        Contact ct = new Contact(FirstName='Test',LastName='Contact',Email='test@timeline.com',AccountId=acct.Id);
        insert ct;
        Task acctTask = new Task(Subject='Test Task',ActivityDate=System.today(),Status='Completed',Description='Test Description',
                                WhatId=acct.Id,WhoId=ct.Id);
        insert acctTask;
        /*
        EmailMessage msg = new EmailMessage(Subject='Test Email',TextBody='Text Body');
        insert msg;
        List<EmailMessageRelation> relToInsert = new List<EmailMessageRelation>();
        relToInsert.add(new EmailMessageRelation(EmailMessageId=msg.Id,RelationId=UserInfo.getUserId(),
                                                RelationType='FromAddress')
                    );
        relToInsert.add(new EmailMessageRelation(EmailMessageId=msg.Id,RelationId=ct.Id,
                                                RelationType='FromAddress')
                    );
        insert relToInsert;
        */
    }

    @isTest static void testGetTimelineItemData(){
        Account acct = [select Id from Account limit 1];
        Timeline_Configuration__c conf = [select Id from Timeline_Configuration__c limit 1];
        TimelineDataResponse resp = RecordTimelineDataProvider.getTimelineItemData(conf.Id, acct.Id);
        System.assert(resp.configuration!=null, 'Timeline configuration is null');
    }

    @isTest static void testGetTimelineItemDataNullInput(){
        TimelineDataResponse resp = RecordTimelineDataProvider.getTimelineItemData(null,null);
        System.assert(resp==null, 'Timeline configuration is not null');
    }

    @isTest static void testGetEmailDetails(){
        Task tsk = [select Id from Task limit 1];
        EmailMessage msg = RecordTimelineDataProvider.getEmailDetails(tsk.Id);
        System.assert(msg==null, 'Message is not null');
    }
}